// Code generated by orange-tv gen model. DO NOT EDIT.

package model

import (
	"context"

	"time"

	"github.com/uptrace/bun"
)

// Actors represents the actors table.
type Actors struct {
	bun.BaseModel `bun:"table:actors,alias:ac"`

	ID uint64 `bun:"id,pk,autoincrement" json:"id"`
	// 演员名称
	Name      string     `bun:"name,notnull,unique" json:"name"`
	CreatedAt *time.Time `bun:"created_at" json:"created_at"`
	UpdatedAt *time.Time `bun:"updated_at" json:"updated_at"`
	// 软删除时间
	DeletedAt   *time.Time     `bun:"deleted_at" json:"deleted_at"`
	VideoActors []*VideoActors `bun:"rel:has-many,join:id=actor_id" json:"-"`
}

var _ bun.BeforeAppendModelHook = (*Actors)(nil)

func (m *Actors) BeforeAppendModel(ctx context.Context, query bun.Query) error {
	now := time.Now()
	switch query.(type) {
	case *bun.InsertQuery:
		m.CreatedAt = &now
		m.UpdatedAt = &now
	case *bun.UpdateQuery:
		m.UpdatedAt = &now
	}
	return nil
}
