// Code generated by orange-tv gen model. DO NOT EDIT.

package model

import (
	"context"

	"time"

	"github.com/uptrace/bun"
)

// AdminLoginLogs represents the admin_login_logs table.
type AdminLoginLogs struct {
	bun.BaseModel `bun:"table:admin_login_logs,alias:all"`

	ID uint32 `bun:"id,pk,autoincrement" json:"id"`
	// 管理员ID
	// Relation: user_id -> Admins(ID)
	UserID uint32 `bun:"user_id,notnull" json:"user_id"`
	// 用户名
	Username string `bun:"username,notnull" json:"username"`
	// IP地址
	IP string `bun:"ip,notnull" json:"ip"`
	// User-Agent
	UserAgent string `bun:"user_agent,notnull" json:"user_agent"`
	// 登录状态：1成功 2失败
	Status    uint8     `bun:"status,notnull" json:"status"`
	CreatedAt time.Time `bun:"created_at,notnull" json:"created_at"`
	Admin     *Admins   `bun:"rel:belongs-to,join:user_id=id" json:"-"`
}

var _ bun.BeforeAppendModelHook = (*AdminLoginLogs)(nil)

func (m *AdminLoginLogs) BeforeAppendModel(ctx context.Context, query bun.Query) error {
	now := time.Now()
	switch query.(type) {
	case *bun.InsertQuery:
		m.CreatedAt = now
	}
	return nil
}
