// Code generated by orange-tv gen model. DO NOT EDIT.

package model

import (
	"context"

	"time"

	"github.com/uptrace/bun"
)

// Advertisements represents the advertisements table.
type Advertisements struct {
	bun.BaseModel `bun:"table:advertisements,alias:ad"`

	ID uint32 `bun:"id,pk,autoincrement" json:"id"`
	// 广告标识，前端用于区分广告位置，唯一
	AdKey string `bun:"ad_key,notnull,unique" json:"ad_key"`
	// 广告标题
	Title string `bun:"title,notnull" json:"title"`
	// 广告场景：video_loading 播放前广告 / general 一般广告
	Scene string `bun:"scene,notnull" json:"scene"`
	// 广告类型：image 图片 / video 视频 / html iframe页面 / code 广告平台代码
	Type string `bun:"type,notnull" json:"type"`
	// 广告素材URL（image/video/html类型使用）
	ContentURL string `bun:"content_url,notnull" json:"content_url"`
	// 广告平台代码（code类型使用，如AdSense的script代码片段）
	ContentCode *string `bun:"content_code" json:"content_code"`
	// 点击跳转链接（code类型不适用）
	LinkURL string `bun:"link_url,notnull" json:"link_url"`
	// 单条展示时长（秒）
	Duration uint32 `bun:"duration,notnull" json:"duration"`
	// 排序，越小越靠前
	Sort uint32 `bun:"sort,notnull" json:"sort"`
	// 1启用 0禁用
	Status    uint8     `bun:"status,notnull" json:"status"`
	CreatedAt time.Time `bun:"created_at,notnull" json:"created_at"`
	UpdatedAt time.Time `bun:"updated_at,notnull" json:"updated_at"`
}

var _ bun.BeforeAppendModelHook = (*Advertisements)(nil)

func (m *Advertisements) BeforeAppendModel(ctx context.Context, query bun.Query) error {
	now := time.Now()
	switch query.(type) {
	case *bun.InsertQuery:
		m.CreatedAt = now
		m.UpdatedAt = now
	case *bun.UpdateQuery:
		m.UpdatedAt = now
	}
	return nil
}
