// Code generated by orange-tv gen model. DO NOT EDIT.

package model

import (
	"context"

	"time"

	"github.com/uptrace/bun"
)

// CollectLogs represents the collect_logs table.
type CollectLogs struct {
	bun.BaseModel `bun:"table:collect_logs,alias:cl"`

	ID uint64 `bun:"id,pk,autoincrement" json:"id"`
	// 采集源ID
	// Relation: source_id -> CollectSources(ID)
	SourceID uint64 `bun:"source_id,notnull" json:"source_id"`
	// 采集状态：1完成 2采集中
	Status    uint8      `bun:"status,notnull" json:"status"`
	CreatedAt *time.Time `bun:"created_at" json:"created_at"`
	// 采集数量（累加）
	CollectCount uint32 `bun:"collect_count,notnull" json:"collect_count"`
	// 耗时(秒)
	DurationSec   uint32          `bun:"duration_sec,notnull" json:"duration_sec"`
	CollectSource *CollectSources `bun:"rel:belongs-to,join:source_id=id" json:"-"`
}

var _ bun.BeforeAppendModelHook = (*CollectLogs)(nil)

func (m *CollectLogs) BeforeAppendModel(ctx context.Context, query bun.Query) error {
	now := time.Now()
	switch query.(type) {
	case *bun.InsertQuery:
		m.CreatedAt = &now
	}
	return nil
}
