// Code generated by orange-tv gen model. DO NOT EDIT.

package model

import (
	"context"

	"time"

	"github.com/uptrace/bun"
)

// Directors represents the directors table.
type Directors struct {
	bun.BaseModel `bun:"table:directors,alias:di"`

	ID uint32 `bun:"id,pk,autoincrement" json:"id"`
	// 导演名称
	Name      string    `bun:"name,notnull,unique" json:"name"`
	CreatedAt time.Time `bun:"created_at,notnull" json:"created_at"`
	UpdatedAt time.Time `bun:"updated_at,notnull" json:"updated_at"`
	// 软删除时间
	DeletedAt      *time.Time        `bun:"deleted_at" json:"deleted_at"`
	VideoDirectors []*VideoDirectors `bun:"rel:has-many,join:id=director_id" json:"-"`
}

var _ bun.BeforeAppendModelHook = (*Directors)(nil)

func (m *Directors) BeforeAppendModel(ctx context.Context, query bun.Query) error {
	now := time.Now()
	switch query.(type) {
	case *bun.InsertQuery:
		m.CreatedAt = now
		m.UpdatedAt = now
	case *bun.UpdateQuery:
		m.UpdatedAt = now
	}
	return nil
}
