// Code generated by orange-tv gen model. DO NOT EDIT.

package model

import (
	"context"

	"time"

	"github.com/uptrace/bun"
)

// LivetvChannels represents the livetv_channels table.
type LivetvChannels struct {
	bun.BaseModel `bun:"table:livetv_channels,alias:lc"`

	ID uint32 `bun:"id,pk,autoincrement" json:"id"`
	// 频道名称
	Name string `bun:"name,notnull" json:"name"`
	// 频道分类
	Category string `bun:"category,notnull" json:"category"`
	// 直播流地址
	StreamURL string `bun:"stream_url,notnull" json:"stream_url"`
	// 频道Logo
	Logo string `bun:"logo,notnull" json:"logo"`
	// 频道描述
	Description string `bun:"description,notnull" json:"description"`
	// 排序
	SortOrder uint32 `bun:"sort_order,notnull" json:"sort_order"`
	// 状态：1启用 0禁用
	Status    uint8     `bun:"status,notnull" json:"status"`
	CreatedAt time.Time `bun:"created_at,notnull" json:"created_at"`
	UpdatedAt time.Time `bun:"updated_at,notnull" json:"updated_at"`
}

var _ bun.BeforeAppendModelHook = (*LivetvChannels)(nil)

func (m *LivetvChannels) BeforeAppendModel(ctx context.Context, query bun.Query) error {
	now := time.Now()
	switch query.(type) {
	case *bun.InsertQuery:
		m.CreatedAt = now
		m.UpdatedAt = now
	case *bun.UpdateQuery:
		m.UpdatedAt = now
	}
	return nil
}
