// Code generated by orange-tv gen model. DO NOT EDIT.

package model

import (
	"context"

	"time"

	"github.com/uptrace/bun"
)

// SystemLogs represents the system_logs table.
type SystemLogs struct {
	bun.BaseModel `bun:"table:system_logs,alias:sl"`

	ID uint32 `bun:"id,pk,autoincrement" json:"id"`
	// 日志级别：1info 2warning 3error 4critical
	Level uint8 `bun:"level,notnull" json:"level"`
	// 模块
	Module string `bun:"module,notnull" json:"module"`
	// 操作
	Action string `bun:"action,notnull" json:"action"`
	// 操作管理员ID
	// Relation: admin_id -> Admins(ID)
	AdminID uint32 `bun:"admin_id,notnull" json:"admin_id"`
	// 日志内容
	Content string `bun:"content,notnull" json:"content"`
	// IP地址
	IPAddress string    `bun:"ip_address,notnull" json:"ip_address"`
	CreatedAt time.Time `bun:"created_at,notnull" json:"created_at"`
	Admin     *Admins   `bun:"rel:belongs-to,join:admin_id=id" json:"-"`
}

var _ bun.BeforeAppendModelHook = (*SystemLogs)(nil)

func (m *SystemLogs) BeforeAppendModel(ctx context.Context, query bun.Query) error {
	now := time.Now()
	switch query.(type) {
	case *bun.InsertQuery:
		m.CreatedAt = now
	}
	return nil
}
