// Code generated by orange-tv gen model. DO NOT EDIT.

package model

import (
	"context"

	"time"

	"github.com/uptrace/bun"
)

// UserLoginLogs represents the user_login_logs table.
type UserLoginLogs struct {
	bun.BaseModel `bun:"table:user_login_logs,alias:ull"`

	ID uint32 `bun:"id,pk,autoincrement" json:"id"`
	// Relation: user_id -> Users(ID)
	UserID uint32 `bun:"user_id,notnull" json:"user_id"`
	// 登录邮箱
	Email     string `bun:"email,notnull" json:"email"`
	IP        string `bun:"ip,notnull" json:"ip"`
	UserAgent string `bun:"user_agent,notnull" json:"user_agent"`
	// 1成功 2失败
	Status    uint8     `bun:"status,notnull" json:"status"`
	CreatedAt time.Time `bun:"created_at,notnull" json:"created_at"`
	User      *Users    `bun:"rel:belongs-to,join:user_id=id" json:"-"`
}

var _ bun.BeforeAppendModelHook = (*UserLoginLogs)(nil)

func (m *UserLoginLogs) BeforeAppendModel(ctx context.Context, query bun.Query) error {
	now := time.Now()
	switch query.(type) {
	case *bun.InsertQuery:
		m.CreatedAt = now
	}
	return nil
}
