// Code generated by orange-tv gen model. DO NOT EDIT.

package model

import (
	"context"

	"time"

	"github.com/uptrace/bun"
)

// UserCommentVotes represents the user_comment_votes table.
type UserCommentVotes struct {
	bun.BaseModel `bun:"table:user_comment_votes,alias:ucv"`

	ID uint32 `bun:"id,pk,autoincrement" json:"id"`
	// Relation: user_id -> Users(ID)
	UserID uint32 `bun:"user_id,notnull,unique:uk_user_comment" json:"user_id"`
	// Relation: comment_id -> VideoComments(ID)
	CommentID uint32 `bun:"comment_id,notnull,unique:uk_user_comment" json:"comment_id"`
	// 1顶 -1踩
	Direction    int8           `bun:"direction,notnull" json:"direction"`
	CreatedAt    time.Time      `bun:"created_at,notnull" json:"created_at"`
	UpdatedAt    time.Time      `bun:"updated_at,notnull" json:"updated_at"`
	VideoComment *VideoComments `bun:"rel:belongs-to,join:comment_id=id" json:"-"`
	User         *Users         `bun:"rel:belongs-to,join:user_id=id" json:"-"`
}

var _ bun.BeforeAppendModelHook = (*UserCommentVotes)(nil)

func (m *UserCommentVotes) BeforeAppendModel(ctx context.Context, query bun.Query) error {
	now := time.Now()
	switch query.(type) {
	case *bun.InsertQuery:
		m.CreatedAt = now
		m.UpdatedAt = now
	case *bun.UpdateQuery:
		m.UpdatedAt = now
	}
	return nil
}
