// Code generated by orange-tv gen model. DO NOT EDIT.

package model

import (
	"context"

	"time"

	"github.com/uptrace/bun"
)

// UserRatings represents the user_ratings table.
type UserRatings struct {
	bun.BaseModel `bun:"table:user_ratings,alias:ur"`

	ID uint32 `bun:"id,pk,autoincrement" json:"id"`
	// Relation: user_id -> Users(ID)
	UserID uint32 `bun:"user_id,notnull,unique:uk_user_video" json:"user_id"`
	// Relation: video_id -> Videos(ID)
	VideoID uint32 `bun:"video_id,notnull,unique:uk_user_video" json:"video_id"`
	// 评分 0.5-10.0
	Score     float64   `bun:"score,notnull" json:"score"`
	CreatedAt time.Time `bun:"created_at,notnull" json:"created_at"`
	UpdatedAt time.Time `bun:"updated_at,notnull" json:"updated_at"`
	User      *Users    `bun:"rel:belongs-to,join:user_id=id" json:"-"`
	Video     *Videos   `bun:"rel:belongs-to,join:video_id=id" json:"-"`
}

var _ bun.BeforeAppendModelHook = (*UserRatings)(nil)

func (m *UserRatings) BeforeAppendModel(ctx context.Context, query bun.Query) error {
	now := time.Now()
	switch query.(type) {
	case *bun.InsertQuery:
		m.CreatedAt = now
		m.UpdatedAt = now
	case *bun.UpdateQuery:
		m.UpdatedAt = now
	}
	return nil
}
