// Code generated by orange-tv gen model. DO NOT EDIT.

package model

import (
	"context"

	"time"

	"github.com/uptrace/bun"
)

// UserFavorites represents the user_favorites table.
type UserFavorites struct {
	bun.BaseModel `bun:"table:user_favorites,alias:uf"`

	ID uint64 `bun:"id,pk,autoincrement" json:"id"`
	// Relation: user_id -> Users(ID)
	UserID uint64 `bun:"user_id,notnull,unique:uk_user_video" json:"user_id"`
	// Relation: video_id -> Videos(ID)
	VideoID   uint64    `bun:"video_id,notnull,unique:uk_user_video" json:"video_id"`
	CreatedAt time.Time `bun:"created_at,notnull" json:"created_at"`
	User      *Users    `bun:"rel:belongs-to,join:user_id=id" json:"-"`
	Video     *Videos   `bun:"rel:belongs-to,join:video_id=id" json:"-"`
}

var _ bun.BeforeAppendModelHook = (*UserFavorites)(nil)

func (m *UserFavorites) BeforeAppendModel(ctx context.Context, query bun.Query) error {
	now := time.Now()
	switch query.(type) {
	case *bun.InsertQuery:
		m.CreatedAt = now
	}
	return nil
}
