// Code generated by orange-tv gen model. DO NOT EDIT.

package model

import (
	"github.com/uptrace/bun"
)

// VideoActors represents the video_actors table.
type VideoActors struct {
	bun.BaseModel `bun:"table:video_actors,alias:va"`

	ID uint32 `bun:"id,pk,autoincrement" json:"id"`
	// 影视ID
	// Relation: video_id -> Videos(ID)
	VideoID uint32 `bun:"video_id,notnull" json:"video_id"`
	// 演员ID
	// Relation: actor_id -> Actors(ID)
	ActorID uint32  `bun:"actor_id,notnull" json:"actor_id"`
	Actor   *Actors `bun:"rel:belongs-to,join:actor_id=id" json:"-"`
	Video   *Videos `bun:"rel:belongs-to,join:video_id=id" json:"-"`
}
