// Code generated by orange-tv gen model. DO NOT EDIT.

package model

import (
	"context"

	"time"

	"github.com/uptrace/bun"
)

// VideoComments represents the video_comments table.
type VideoComments struct {
	bun.BaseModel `bun:"table:video_comments,alias:vc"`

	ID uint32 `bun:"id,pk,autoincrement" json:"id"`
	// Relation: video_id -> Videos(ID)
	VideoID uint32 `bun:"video_id,notnull" json:"video_id"`
	// Relation: user_id -> Users(ID)
	UserID uint32 `bun:"user_id,notnull" json:"user_id"`
	// 父评论ID，0为顶级
	// Relation: parent_id -> VideoComments(ID)
	ParentID uint32 `bun:"parent_id,notnull" json:"parent_id"`
	Content  string `bun:"content,notnull" json:"content"`
	// 0隐藏 1正常
	Status           uint8               `bun:"status,notnull" json:"status"`
	LikeCount        uint32              `bun:"like_count,notnull" json:"like_count"`
	DislikeCount     uint32              `bun:"dislike_count,notnull" json:"dislike_count"`
	CreatedAt        time.Time           `bun:"created_at,notnull" json:"created_at"`
	UpdatedAt        time.Time           `bun:"updated_at,notnull" json:"updated_at"`
	UserCommentVotes []*UserCommentVotes `bun:"rel:has-many,join:id=comment_id" json:"-"`
	Parent           *VideoComments      `bun:"rel:belongs-to,join:parent_id=id" json:"-"`
	Replies          []*VideoComments    `bun:"rel:has-many,join:id=parent_id" json:"-"`
	User             *Users              `bun:"rel:belongs-to,join:user_id=id" json:"-"`
	Video            *Videos             `bun:"rel:belongs-to,join:video_id=id" json:"-"`
}

var _ bun.BeforeAppendModelHook = (*VideoComments)(nil)

func (m *VideoComments) BeforeAppendModel(ctx context.Context, query bun.Query) error {
	now := time.Now()
	switch query.(type) {
	case *bun.InsertQuery:
		m.CreatedAt = now
		m.UpdatedAt = now
	case *bun.UpdateQuery:
		m.UpdatedAt = now
	}
	return nil
}
